#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

swift build -c release --arch arm64 2>&1 | grep -E "error|Build complete" || true
BIN="$(swift build -c release --arch arm64 --show-bin-path)"
WORK="$(mktemp -d)"
PORT="${PORT:-18640}"
PID=""
cleanup() {
    [[ -n "$PID" ]] && kill "$PID" 2>/dev/null || true
    rm -rf "$WORK"
}
trap cleanup EXIT

fail() { echo "FAIL: $*"; exit 1; }

mkdir -p "$WORK/sink"
"$BIN/tmt88v-service" --port "$PORT" --sink "$WORK/sink/" 2> "$WORK/service.log" > "$WORK/service.out" &
PID=$!
for _ in $(seq 1 50); do grep -q printer-uri "$WORK/service.out" 2>/dev/null && break; sleep 0.1; done
URI="ipp://127.0.0.1:$PORT/ipp/print"

echo "== listening sockets (must be loopback only)"
LISTEN="$(lsof -nP -a -p "$PID" -iTCP -sTCP:LISTEN | tail -n +2)"
echo "$LISTEN"
echo "$LISTEN" | grep -vE '127\.0\.0\.1:|\[::1\]:' && fail "non-loopback listener" || true

echo "== ipptool protocol checks"
ipptool -t "$URI" Tests/ipptool/get-printer-attributes.test | tail -3

echo "== driverless PPD generated by libcups from our attributes"
clang -Wno-deprecated-declarations scripts/dev/mkppd.c -o "$WORK/mkppd" -lcups
cp "$("$WORK/mkppd" "$PORT")" "$WORK/generated.ppd"
grep -E '^\*(DefaultPageSize|PageSize|cupsFilter2|DefaultResolution|ParamCustomPageSize Width|ParamCustomPageSize Height|HWMargins)' "$WORK/generated.ppd"

printf 'RECEIPT TEST LINE 1\nTotal: 42.00 DKK\nThank you\n' > "$WORK/in.txt"
(for i in $(seq 1 120); do echo "Line $i of a long multi page receipt"; done) > "$WORK/long.txt"
cupsfilter -m application/pdf "$WORK/long.txt" > "$WORK/long.pdf" 2>/dev/null

cat > "$WORK/printjob.test" <<'T'
{
	NAME "Print-Job URF"
	OPERATION Print-Job
	GROUP operation-attributes-tag
	ATTR charset attributes-charset utf-8
	ATTR language attributes-natural-language en
	ATTR uri printer-uri $uri
	ATTR name job-name "e2e"
	ATTR mimeMediaType document-format image/urf
	FILE $filename
	STATUS successful-ok
	EXPECT job-id
}
T

submit() {
    cupsfilter -p "$WORK/generated.ppd" -m image/urf -o PageSize=72x297mm.Borderless "$1" > "$WORK/$2.urf" 2>/dev/null
    ipptool -t -d filename="$WORK/$2.urf" "$URI" "$WORK/printjob.test" | grep -E "PASS|FAIL"
}

echo "== text job and two-page PDF job through macOS CUPS filters"
submit "$WORK/in.txt" text
submit "$WORK/long.pdf" pdf
for _ in $(seq 1 50); do [[ -f "$WORK/sink/job-2.escpos" ]] && break; sleep 0.1; done

for job in 1 2; do
    echo "-- job-$job.escpos"
    "$BIN/tmt88v-raster-test" --decode "$WORK/sink/job-$job.escpos" | tee "$WORK/decode$job.txt"
    grep -q "512x" "$WORK/decode$job.txt" || fail "job $job not 512 wide"
    grep -q "cut true" "$WORK/decode$job.txt" || fail "job $job not cut"
done

echo "== job log events"
grep -E '"event":"job_(completed|failed)"' "$WORK/service.log"

kill -TERM "$PID"; wait "$PID" 2>/dev/null || true
PID=""
lsof -nP -iTCP:"$PORT" -sTCP:LISTEN | grep -q . && fail "port still listening after SIGTERM"
echo "PASS: end-to-end sink path verified (no USB used)"
